spring.application.name=limo-be

server.port=8080


# JPA Configuration
spring.datasource.driver-class-name=org.postgresql.Driver

#spring.jpa.hibernate.ddl-auto=update # 개발 시 'update' 사용, 프로덕션 시 'none' 사용
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect


# Azure Blob Storage Configuration (SAS Token 사용으로 변경)
azure.storage.account.name=stalimoapps
azure.storage.container.name=lake-image

### Azure Event Hubs Configuration
# Azure Event Hubs Configuration
azure.eventhubs.name=limo-iot-evt-sensor
azure.eventhubs.consumer.group=sensor-be

# Redis 설정
#handon-comm-redis.redis.cache.windows.net:6380,password=9DzrzwxZ2BFscRrZtWeqY6292gj2GEatVAzCaAWlYhk=,ssl=True,abortConnect=False
spring.data.redis.host=handon-comm-redis.redis.cache.windows.net
spring.data.redis.port=6380
spring.data.redis.password=tOoNkru75naRxx5XjybYis8NjKBtD6e07AzCaGHurKM=
spring.data.redis.ssl.enabled=true


# Lettuce 클라이언트 설정 (connection-pool 사용 시)
# spring.data.redis.lettuce.pool.max-active=8
# spring.data.redis.lettuce.pool.max-wait=-1
# spring.data.redis.lettuce.pool.max-idle=8
# spring.data.redis.lettuce.pool.min-idle=0


# CORS Configuration for Frontend
#spring.web.cors.allowed-origins=http://localhost:8080,https://limoapi-bkd5e9huhja0defa.koreacentral-01.azurewebsites.net
# Vue.js 프론트엔드 URL (로컬 및 Azure App Service URL 포함)
#spring.web.cors.allowed-methods=GET,POST,PUT,DELETE,OPTIONS
#spring.web.cors.allowed-headers=*
#spring.web.cors.allow-credentials=true
